Click button show infor
<form id="loginform" method="post">
    <h2> Vui long nhap ID :</h2>
    <input type="number" id="idtest" style="width:300px;" placeholder="Nhập id từ 0 đến 30">
    <input type="submit" id="click" value="View customers have same custom prefix">
</form>
<form id="popup-mpdal" method="post">

</form>
<script>

    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Magenest ParttimePlus',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
            $("#click").on('click', function () {
                $('#loginform').submit(function () {
                    return false;
                });
                var id = $('#idtest').val();

                $.ajax({
                    type: "post",
                    url: "<?php echo $block->getUrl('PartTimePlus/Ajax/Handle') ?>",
                    data: 'id=' + id,
                    success: function (data) {
                        console.log(data)
                        $('#popup-mpdal').html(data);
                    }
                });
                $("#popup-mpdal").modal("openModal");
            });

        }
    );

</script>

