<form>
    <div id="block">
        <label class="left-additional">User</label>
        <div class="right-additional" id="outer">
            <input type="text" class="input-text required-entry" maxlength="255" >
        </div>
    </div>
        <p/>
    <div id="block">
        <label class="left-additional">Password</label>
        <div class="right-additional" id="outer">
            <input type="password" class="input-text required-entry" maxlength="255">
        </div>
    </div>
</form>
